/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipecookbook.gui;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import recipecookbook.models.Ingredient;
import recipecookbook.models.Recipe;
import recipecookbook.services.IngredientService;
import recipecookbook.services.RecipeIngredientService;
import recipecookbook.services.RecipeMealService;
import recipecookbook.services.RecipeService;

public class RecipePanel extends javax.swing.JPanel {
    public boolean initialized = false;
    DefaultListModel recipeListModel;
    DefaultListModel ingredientListModel;
    DefaultComboBoxModel categoryComboBoxModel;

    /**
     * Creates new form RecipePanel
     */
    public RecipePanel() {
        initComponents();
        categoryLabel.setText("");
        instructionsLabel.setText("");
        initialize();
    }
    
    public void initialize() {
        System.out.println("Initializing RecipePanel");
        List<Recipe> recipes = RecipeService.getAllRecipes();
        loadRecipesAndCategories(recipes, true); 
        loadIngredients();
        
        initialized = true;
    }
    
    public void loadRecipesAndCategories(List<Recipe> recipes, boolean firstRun) {
        recipeListModel = new DefaultListModel();
        for(Recipe recipe : recipes) {
            recipeListModel.addElement(recipe);
        }
        recipeJList.setModel(recipeListModel);
        
        //if this is the first time loading the form, grab all possible categories
        if(firstRun) {
            categoryComboBoxModel = new DefaultComboBoxModel();
            categoryComboBoxModel.addElement(""); //add empty string so user doesn't have to choose a category
            for(Recipe recipe : recipes) {
                categoryComboBoxModel.addElement(recipe.getCategory());
            }
            categoryComboBox.setModel(categoryComboBoxModel);
        }
    }
    
    public void loadIngredients() {
        List<Ingredient> ingredients = IngredientService.getAllIngredients();
        
        ingredientListModel = new DefaultListModel();
        DefaultListModel recipeIngredientListModel = new DefaultListModel();
        for(Ingredient ingredient : ingredients) {
            ingredientListModel.addElement(ingredient);
            recipeIngredientListModel.addElement(ingredient);
        }
        
        ingredientJList.setModel(ingredientListModel);
        addIngredientList.setModel(recipeIngredientListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recipeJList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ingredientTextArea = new javax.swing.JTextArea();
        searchRecipeButton = new javax.swing.JButton();
        categoryComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ingredientJList = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        instructionsLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        newRecipeNameTextField = new javax.swing.JTextField();
        newCategoryNameTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        newInstructionsTextArea = new javax.swing.JTextArea();
        saveRecipeButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        addIngredientList = new javax.swing.JList<>();
        deleteRecipeButton = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Recipes");

        recipeJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                recipeJListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(recipeJList);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Category:");

        categoryLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        categoryLabel.setText("test");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Ingredients");

        ingredientTextArea.setColumns(20);
        ingredientTextArea.setLineWrap(true);
        ingredientTextArea.setRows(5);
        ingredientTextArea.setPreferredSize(new java.awt.Dimension(160, 80));
        jScrollPane2.setViewportView(ingredientTextArea);

        searchRecipeButton.setText("Search");
        searchRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRecipeButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingredients");

        jLabel5.setText("Category");

        jScrollPane3.setViewportView(ingredientJList);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Instructions:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Search");

        instructionsLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        instructionsLabel.setText("Instructions");
        instructionsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        instructionsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        instructionsLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Add Recipe");

        jLabel9.setText("Name:");

        jLabel10.setText("Category:");

        jLabel11.setText("Instructions:");

        newInstructionsTextArea.setColumns(20);
        newInstructionsTextArea.setLineWrap(true);
        newInstructionsTextArea.setRows(5);
        jScrollPane4.setViewportView(newInstructionsTextArea);

        saveRecipeButton.setText("Save Recipe");
        saveRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRecipeButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Add Ingredients");

        jScrollPane5.setViewportView(addIngredientList);

        deleteRecipeButton.setText("Delete");
        deleteRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecipeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newCategoryNameTextField)
                            .addComponent(newRecipeNameTextField)
                            .addComponent(jScrollPane4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveRecipeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteRecipeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(categoryLabel))
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5))
                                    .addGap(214, 214, 214))
                                .addComponent(jScrollPane3)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchRecipeButton))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(instructionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteRecipeButton)
                            .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchRecipeButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(instructionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newRecipeNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(saveRecipeButton)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(newCategoryNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane4)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void recipeJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_recipeJListValueChanged
        Recipe recipe = recipeJList.getSelectedValue();

        if(recipe != null) {
            Set<Ingredient> ingredients = IngredientService.getIngredientByRecipe(recipe);

            StringBuilder ingredientTextBuilder = new StringBuilder();
            for(Ingredient ingredient : ingredients) {
                ingredientTextBuilder.append(ingredient.toString());
                ingredientTextBuilder.append("\n");
            }

            ingredientTextArea.setText(ingredientTextBuilder.toString());

            //update the category label
            categoryLabel.setText(recipe.getCategory());

            //update the instructions label
            StringBuilder instructionTextBuilder = new StringBuilder();
            instructionTextBuilder.append("<html><body>");
            String[] instructions = recipe.getInstructions().split("\n");
            for(int i = 0; i < instructions.length; i++) {
                instructionTextBuilder.append(instructions[i]);
                
                if(i < instructions.length - 1) {
                    instructionTextBuilder.append("<br>");
                }
            }
            instructionTextBuilder.append("</body></html>");
            instructionsLabel.setText(instructionTextBuilder.toString());
        }
    }//GEN-LAST:event_recipeJListValueChanged

    private void searchRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRecipeButtonActionPerformed
        List<Ingredient> selectedIngredients = ingredientJList.getSelectedValuesList();
        String category = (String) categoryComboBox.getSelectedItem();

        Set<Recipe> recipeSet = RecipeService.getRecipeByIngredientsAndCategory(selectedIngredients, category);
        List<Recipe> recipes = new ArrayList<>();
        recipes.addAll(recipeSet);

        loadRecipesAndCategories(recipes, false);
    }//GEN-LAST:event_searchRecipeButtonActionPerformed

    private void saveRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRecipeButtonActionPerformed
        Recipe recipe = new Recipe();
        List<Ingredient> selectedIngredients = addIngredientList.getSelectedValuesList();
        if(!newRecipeNameTextField.getText().isEmpty()
                && !newCategoryNameTextField.getText().isEmpty()
                && !newInstructionsTextArea.getText().isEmpty()
                && selectedIngredients != null
                && !selectedIngredients.isEmpty()) {
            
            recipe.setName(newRecipeNameTextField.getText());
            recipe.setCategory(newCategoryNameTextField.getText());
            recipe.setInstructions(newInstructionsTextArea.getText());
            RecipeService.createNewRecipe(recipe);
            RecipeIngredientService.addIngredientsToRecipe(recipe, selectedIngredients);
            
            newRecipeNameTextField.setText("");
            newCategoryNameTextField.setText("");
            newInstructionsTextArea.setText("");
            initialize();
        } else {
            System.out.println("Not all fields filled out");
        }
        
    }//GEN-LAST:event_saveRecipeButtonActionPerformed

    private void deleteRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRecipeButtonActionPerformed
        Recipe recipe = recipeJList.getSelectedValue();
        
        if(recipe != null) {
            RecipeIngredientService.deleteByRecipe(recipe);
            RecipeMealService.deleteRecipeMealByRecipe(recipe);
            RecipeService.deleteRecipe(recipe);
            
            initialize();
        }
    }//GEN-LAST:event_deleteRecipeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Ingredient> addIngredientList;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton deleteRecipeButton;
    private javax.swing.JList<Ingredient> ingredientJList;
    private javax.swing.JTextArea ingredientTextArea;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField newCategoryNameTextField;
    private javax.swing.JTextArea newInstructionsTextArea;
    private javax.swing.JTextField newRecipeNameTextField;
    private javax.swing.JList<Recipe> recipeJList;
    private javax.swing.JButton saveRecipeButton;
    private javax.swing.JButton searchRecipeButton;
    // End of variables declaration//GEN-END:variables
}
