/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipecookbook.gui;

/**
 *
 * @author MUKESH
 */
public class WeeklyMealFrame extends javax.swing.JFrame {

    /**
     * Creates new form WeeklyMealFrame
     */
    public WeeklyMealFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModayCheckBox = new javax.swing.JCheckBox();
        TuesdayCheckBox = new javax.swing.JCheckBox();
        WednesdayCheckBox = new javax.swing.JCheckBox();
        ThursdayCheckBox = new javax.swing.JCheckBox();
        FridayCheckBox = new javax.swing.JCheckBox();
        SaturdayCheckBox = new javax.swing.JCheckBox();
        SundayCheckBox = new javax.swing.JCheckBox();
        BreakfastComboBox = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        ChangeBreakfast = new javax.swing.JButton();
        ChangeLunch = new javax.swing.JButton();
        ChangeDinner = new javax.swing.JButton();
        GenerateList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ModayCheckBox.setSelected(true);
        ModayCheckBox.setText("Monday");
        ModayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModayCheckBoxActionPerformed(evt);
            }
        });

        TuesdayCheckBox.setSelected(true);
        TuesdayCheckBox.setActionCommand("Tuesday");
        TuesdayCheckBox.setDoubleBuffered(true);
        TuesdayCheckBox.setLabel("Tuesday");
        TuesdayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesdayCheckBoxActionPerformed(evt);
            }
        });

        WednesdayCheckBox.setText("Wednesday");

        ThursdayCheckBox.setText("Thursday");
        ThursdayCheckBox.setAutoscrolls(true);

        FridayCheckBox.setText("Friday");

        SaturdayCheckBox.setText("Saturday");

        SundayCheckBox.setText("Sunday");
        SundayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SundayCheckBoxActionPerformed(evt);
            }
        });

        BreakfastComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breakfast" }));
        BreakfastComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreakfastComboBoxActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunch" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinner" }));

        ChangeBreakfast.setText("Change");

        ChangeLunch.setText("Change");

        ChangeDinner.setText("Change");

        GenerateList.setText("Generate List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FridayCheckBox)
                            .addComponent(WednesdayCheckBox)
                            .addComponent(ModayCheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SundayCheckBox)
                                    .addComponent(TuesdayCheckBox)
                                    .addComponent(ThursdayCheckBox))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BreakfastComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ChangeBreakfast)
                                        .addComponent(ChangeLunch))
                                    .addComponent(ChangeDinner))))
                        .addContainerGap(103, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaturdayCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GenerateList)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(SundayCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BreakfastComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeBreakfast))))
                .addGap(18, 18, 18)
                .addComponent(ModayCheckBox)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TuesdayCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeLunch))))
                .addGap(18, 18, 18)
                .addComponent(WednesdayCheckBox)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ThursdayCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeDinner))))
                .addGap(18, 18, 18)
                .addComponent(FridayCheckBox)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SaturdayCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(GenerateList)))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModayCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModayCheckBoxActionPerformed

    private void TuesdayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesdayCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuesdayCheckBoxActionPerformed

    private void SundayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SundayCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SundayCheckBoxActionPerformed

    private void BreakfastComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreakfastComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BreakfastComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeeklyMealFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeeklyMealFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeeklyMealFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeeklyMealFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeeklyMealFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BreakfastComboBox;
    private javax.swing.JButton ChangeBreakfast;
    private javax.swing.JButton ChangeDinner;
    private javax.swing.JButton ChangeLunch;
    private javax.swing.JCheckBox FridayCheckBox;
    private javax.swing.JButton GenerateList;
    private javax.swing.JCheckBox ModayCheckBox;
    private javax.swing.JCheckBox SaturdayCheckBox;
    private javax.swing.JCheckBox SundayCheckBox;
    private javax.swing.JCheckBox ThursdayCheckBox;
    private javax.swing.JCheckBox TuesdayCheckBox;
    private javax.swing.JCheckBox WednesdayCheckBox;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    // End of variables declaration//GEN-END:variables
}
